// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAdminSession = `-- name: CreateAdminSession :exec
INSERT INTO admin_sessions (id, admin_user_id, expires_at)
VALUES ($1, $2, $3)
`

type CreateAdminSessionParams struct {
	ID          string
	AdminUserID string
	ExpiresAt   pgtype.Timestamptz
}

func (q *Queries) CreateAdminSession(ctx context.Context, arg CreateAdminSessionParams) error {
	_, err := q.db.Exec(ctx, createAdminSession, arg.ID, arg.AdminUserID, arg.ExpiresAt)
	return err
}

const createAdminUser = `-- name: CreateAdminUser :one
INSERT INTO admin_users (id, email, password_hash)
VALUES ($1, $2, $3)
ON CONFLICT (email) DO NOTHING
RETURNING id, email, password_hash, created_at
`

type CreateAdminUserParams struct {
	ID           string
	Email        string
	PasswordHash string
}

func (q *Queries) CreateAdminUser(ctx context.Context, arg CreateAdminUserParams) (AdminUser, error) {
	row := q.db.QueryRow(ctx, createAdminUser, arg.ID, arg.Email, arg.PasswordHash)
	var i AdminUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAdminSession = `-- name: DeleteAdminSession :exec
DELETE FROM admin_sessions WHERE id = $1
`

func (q *Queries) DeleteAdminSession(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteAdminSession, id)
	return err
}

const getAdminSession = `-- name: GetAdminSession :one
SELECT id, admin_user_id, expires_at, created_at
FROM admin_sessions
WHERE id = $1 AND expires_at > now()
`

func (q *Queries) GetAdminSession(ctx context.Context, id string) (AdminSession, error) {
	row := q.db.QueryRow(ctx, getAdminSession, id)
	var i AdminSession
	err := row.Scan(
		&i.ID,
		&i.AdminUserID,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getAdminUserByEmail = `-- name: GetAdminUserByEmail :one
SELECT id, email, password_hash, created_at
FROM admin_users
WHERE email = $1
`

func (q *Queries) GetAdminUserByEmail(ctx context.Context, email string) (AdminUser, error) {
	row := q.db.QueryRow(ctx, getAdminUserByEmail, email)
	var i AdminUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}

const insertAuditLog = `-- name: InsertAuditLog :exec
INSERT INTO audit_logs (id, actor, action, subject_type, subject_id, detail)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertAuditLogParams struct {
	ID          string
	Actor       string
	Action      string
	SubjectType string
	SubjectID   string
	Detail      []byte
}

func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error {
	_, err := q.db.Exec(ctx, insertAuditLog,
		arg.ID,
		arg.Actor,
		arg.Action,
		arg.SubjectType,
		arg.SubjectID,
		arg.Detail,
	)
	return err
}

const listAuditLogs = `-- name: ListAuditLogs :many
SELECT id, actor, action, subject_type, subject_id, detail, created_at
FROM audit_logs
ORDER BY created_at DESC
LIMIT $1
`

func (q *Queries) ListAuditLogs(ctx context.Context, limit int32) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLogs, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.Actor,
			&i.Action,
			&i.SubjectType,
			&i.SubjectID,
			&i.Detail,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
