// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: idempotency.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteExpiredIdempotency = `-- name: DeleteExpiredIdempotency :execrows
DELETE FROM idempotency_keys WHERE expires_at < now()
`

func (q *Queries) DeleteExpiredIdempotency(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredIdempotency)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getIdempotency = `-- name: GetIdempotency :one
SELECT key, request_hash, response_snapshot, payment_id, expires_at, created_at
FROM idempotency_keys
WHERE key = $1
`

func (q *Queries) GetIdempotency(ctx context.Context, key string) (IdempotencyKey, error) {
	row := q.db.QueryRow(ctx, getIdempotency, key)
	var i IdempotencyKey
	err := row.Scan(
		&i.Key,
		&i.RequestHash,
		&i.ResponseSnapshot,
		&i.PaymentID,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getIdempotencyByPaymentID = `-- name: GetIdempotencyByPaymentID :one
SELECT key, request_hash, response_snapshot, payment_id, expires_at, created_at
FROM idempotency_keys
WHERE payment_id = $1
`

func (q *Queries) GetIdempotencyByPaymentID(ctx context.Context, paymentID *string) (IdempotencyKey, error) {
	row := q.db.QueryRow(ctx, getIdempotencyByPaymentID, paymentID)
	var i IdempotencyKey
	err := row.Scan(
		&i.Key,
		&i.RequestHash,
		&i.ResponseSnapshot,
		&i.PaymentID,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const setIdempotencyResponse = `-- name: SetIdempotencyResponse :exec
UPDATE idempotency_keys
SET response_snapshot = $2, payment_id = COALESCE($3, payment_id)
WHERE key = $1
`

type SetIdempotencyResponseParams struct {
	Key              string
	ResponseSnapshot []byte
	PaymentID        *string
}

func (q *Queries) SetIdempotencyResponse(ctx context.Context, arg SetIdempotencyResponseParams) error {
	_, err := q.db.Exec(ctx, setIdempotencyResponse, arg.Key, arg.ResponseSnapshot, arg.PaymentID)
	return err
}

const tryInsertIdempotency = `-- name: TryInsertIdempotency :one
INSERT INTO idempotency_keys (key, request_hash, payment_id, expires_at)
VALUES ($1, $2, $3, $4)
ON CONFLICT (key) DO NOTHING
RETURNING key, request_hash, response_snapshot, payment_id, expires_at, created_at
`

type TryInsertIdempotencyParams struct {
	Key         string
	RequestHash []byte
	PaymentID   *string
	ExpiresAt   pgtype.Timestamptz
}

// 冪等性キー行を挿入する。既存キーとの競合時は0行を返す（呼び出し側でGetIdempotencyを実行して結果を返却する）
func (q *Queries) TryInsertIdempotency(ctx context.Context, arg TryInsertIdempotencyParams) (IdempotencyKey, error) {
	row := q.db.QueryRow(ctx, tryInsertIdempotency,
		arg.Key,
		arg.RequestHash,
		arg.PaymentID,
		arg.ExpiresAt,
	)
	var i IdempotencyKey
	err := row.Scan(
		&i.Key,
		&i.RequestHash,
		&i.ResponseSnapshot,
		&i.PaymentID,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}
