// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ledger.sql

package sqlc

import (
	"context"
)

const insertLedgerEntry = `-- name: InsertLedgerEntry :exec
INSERT INTO ledger_entries (id, transfer_id, account, side, amount_jpy, payment_id)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (transfer_id, side) DO NOTHING
`

type InsertLedgerEntryParams struct {
	ID         string
	TransferID string
	Account    LedgerAccount
	Side       LedgerSide
	AmountJpy  int64
	PaymentID  string
}

// transfer_id + side の複合UNIQUE制約により、Outboxリトライ再実行では二重記帳を防ぐ
func (q *Queries) InsertLedgerEntry(ctx context.Context, arg InsertLedgerEntryParams) error {
	_, err := q.db.Exec(ctx, insertLedgerEntry,
		arg.ID,
		arg.TransferID,
		arg.Account,
		arg.Side,
		arg.AmountJpy,
		arg.PaymentID,
	)
	return err
}

const listLedgerByPayment = `-- name: ListLedgerByPayment :many
SELECT id, transfer_id, account, side, amount_jpy, payment_id, created_at
FROM ledger_entries
WHERE payment_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListLedgerByPayment(ctx context.Context, paymentID string) ([]LedgerEntry, error) {
	rows, err := q.db.Query(ctx, listLedgerByPayment, paymentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LedgerEntry{}
	for rows.Next() {
		var i LedgerEntry
		if err := rows.Scan(
			&i.ID,
			&i.TransferID,
			&i.Account,
			&i.Side,
			&i.AmountJpy,
			&i.PaymentID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumLedgerBalance = `-- name: SumLedgerBalance :one
SELECT
  COALESCE(SUM(CASE WHEN side = 'debit' THEN amount_jpy ELSE 0 END), 0)::BIGINT AS debit_total,
  COALESCE(SUM(CASE WHEN side = 'credit' THEN amount_jpy ELSE 0 END), 0)::BIGINT AS credit_total
FROM ledger_entries
WHERE account = $1
`

type SumLedgerBalanceRow struct {
	DebitTotal  int64
	CreditTotal int64
}

func (q *Queries) SumLedgerBalance(ctx context.Context, account LedgerAccount) (SumLedgerBalanceRow, error) {
	row := q.db.QueryRow(ctx, sumLedgerBalance, account)
	var i SumLedgerBalanceRow
	err := row.Scan(&i.DebitTotal, &i.CreditTotal)
	return i, err
}
