// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type LedgerAccount string

const (
	LedgerAccountPspReceivable LedgerAccount = "psp_receivable"
	LedgerAccountSales         LedgerAccount = "sales"
	LedgerAccountRefunds       LedgerAccount = "refunds"
)

func (e *LedgerAccount) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = LedgerAccount(s)
	case string:
		*e = LedgerAccount(s)
	default:
		return fmt.Errorf("unsupported scan type for LedgerAccount: %T", src)
	}
	return nil
}

type NullLedgerAccount struct {
	LedgerAccount LedgerAccount
	Valid         bool // Valid is true if LedgerAccount is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullLedgerAccount) Scan(value interface{}) error {
	if value == nil {
		ns.LedgerAccount, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.LedgerAccount.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullLedgerAccount) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.LedgerAccount), nil
}

type LedgerSide string

const (
	LedgerSideDebit  LedgerSide = "debit"
	LedgerSideCredit LedgerSide = "credit"
)

func (e *LedgerSide) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = LedgerSide(s)
	case string:
		*e = LedgerSide(s)
	default:
		return fmt.Errorf("unsupported scan type for LedgerSide: %T", src)
	}
	return nil
}

type NullLedgerSide struct {
	LedgerSide LedgerSide
	Valid      bool // Valid is true if LedgerSide is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullLedgerSide) Scan(value interface{}) error {
	if value == nil {
		ns.LedgerSide, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.LedgerSide.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullLedgerSide) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.LedgerSide), nil
}

type OutboxStatus string

const (
	OutboxStatusPending    OutboxStatus = "pending"
	OutboxStatusProcessing OutboxStatus = "processing"
	OutboxStatusDone       OutboxStatus = "done"
	OutboxStatusFailed     OutboxStatus = "failed"
)

func (e *OutboxStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OutboxStatus(s)
	case string:
		*e = OutboxStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for OutboxStatus: %T", src)
	}
	return nil
}

type NullOutboxStatus struct {
	OutboxStatus OutboxStatus
	Valid        bool // Valid is true if OutboxStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOutboxStatus) Scan(value interface{}) error {
	if value == nil {
		ns.OutboxStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OutboxStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOutboxStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OutboxStatus), nil
}

type PaymentState string

const (
	PaymentStateCreated           PaymentState = "created"
	PaymentStateAuthorized        PaymentState = "authorized"
	PaymentStateCaptured          PaymentState = "captured"
	PaymentStateCanceled          PaymentState = "canceled"
	PaymentStateExpired           PaymentState = "expired"
	PaymentStateFailed            PaymentState = "failed"
	PaymentStatePartiallyRefunded PaymentState = "partially_refunded"
	PaymentStateRefunded          PaymentState = "refunded"
)

func (e *PaymentState) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PaymentState(s)
	case string:
		*e = PaymentState(s)
	default:
		return fmt.Errorf("unsupported scan type for PaymentState: %T", src)
	}
	return nil
}

type NullPaymentState struct {
	PaymentState PaymentState
	Valid        bool // Valid is true if PaymentState is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPaymentState) Scan(value interface{}) error {
	if value == nil {
		ns.PaymentState, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PaymentState.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPaymentState) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PaymentState), nil
}

type WebhookStatus string

const (
	WebhookStatusReceived  WebhookStatus = "received"
	WebhookStatusProcessed WebhookStatus = "processed"
	WebhookStatusFailed    WebhookStatus = "failed"
)

func (e *WebhookStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = WebhookStatus(s)
	case string:
		*e = WebhookStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for WebhookStatus: %T", src)
	}
	return nil
}

type NullWebhookStatus struct {
	WebhookStatus WebhookStatus
	Valid         bool // Valid is true if WebhookStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullWebhookStatus) Scan(value interface{}) error {
	if value == nil {
		ns.WebhookStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.WebhookStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullWebhookStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.WebhookStatus), nil
}

type AdminSession struct {
	ID          string
	AdminUserID string
	ExpiresAt   pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
}

type AdminUser struct {
	ID           string
	Email        string
	PasswordHash string
	CreatedAt    pgtype.Timestamptz
}

type AuditLog struct {
	ID          string
	Actor       string
	Action      string
	SubjectType string
	SubjectID   string
	Detail      []byte
	CreatedAt   pgtype.Timestamptz
}

type IdempotencyKey struct {
	Key              string
	RequestHash      []byte
	ResponseSnapshot []byte
	PaymentID        *string
	ExpiresAt        pgtype.Timestamptz
	CreatedAt        pgtype.Timestamptz
}

type LedgerEntry struct {
	ID         string
	TransferID string
	Account    LedgerAccount
	Side       LedgerSide
	AmountJpy  int64
	PaymentID  string
	CreatedAt  pgtype.Timestamptz
}

type OutboxEvent struct {
	ID            string
	EventType     string
	Payload       []byte
	Status        OutboxStatus
	RetryCount    int32
	NextAttemptAt pgtype.Timestamptz
	LastError     *string
	CreatedAt     pgtype.Timestamptz
	ProcessedAt   pgtype.Timestamptz
}

type Payment struct {
	ID                    string
	ProductID             string
	AmountJpy             int64
	RefundedJpy           int64
	State                 PaymentState
	StripePaymentIntentID *string
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
}

type PaymentTransition struct {
	ID        string
	PaymentID string
	FromState PaymentState
	ToState   PaymentState
	Event     string
	Actor     string
	CreatedAt pgtype.Timestamptz
}

type Product struct {
	ID              string
	Name            string
	PriceJpy        int64
	TokushoSnapshot []byte
	CreatedAt       pgtype.Timestamptz
}

type WebhookEvent struct {
	ID            string
	StripeEventID string
	EventType     string
	Payload       []byte
	Status        WebhookStatus
	ReceivedAt    pgtype.Timestamptz
	ProcessedAt   pgtype.Timestamptz
}
