// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: outbox.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const enqueueOutboxEvent = `-- name: EnqueueOutboxEvent :one
INSERT INTO outbox_events (id, event_type, payload, next_attempt_at)
VALUES ($1, $2, $3, now())
RETURNING id, event_type, payload, status, retry_count, next_attempt_at, created_at, processed_at
`

type EnqueueOutboxEventParams struct {
	ID        string
	EventType string
	Payload   []byte
}

type EnqueueOutboxEventRow struct {
	ID            string
	EventType     string
	Payload       []byte
	Status        OutboxStatus
	RetryCount    int32
	NextAttemptAt pgtype.Timestamptz
	CreatedAt     pgtype.Timestamptz
	ProcessedAt   pgtype.Timestamptz
}

func (q *Queries) EnqueueOutboxEvent(ctx context.Context, arg EnqueueOutboxEventParams) (EnqueueOutboxEventRow, error) {
	row := q.db.QueryRow(ctx, enqueueOutboxEvent, arg.ID, arg.EventType, arg.Payload)
	var i EnqueueOutboxEventRow
	err := row.Scan(
		&i.ID,
		&i.EventType,
		&i.Payload,
		&i.Status,
		&i.RetryCount,
		&i.NextAttemptAt,
		&i.CreatedAt,
		&i.ProcessedAt,
	)
	return i, err
}

const fetchPendingOutbox = `-- name: FetchPendingOutbox :many
SELECT id, event_type, payload, status, retry_count, next_attempt_at, created_at, processed_at
FROM outbox_events
WHERE status = 'pending' AND next_attempt_at <= now()
ORDER BY next_attempt_at ASC
LIMIT $1
FOR UPDATE SKIP LOCKED
`

type FetchPendingOutboxRow struct {
	ID            string
	EventType     string
	Payload       []byte
	Status        OutboxStatus
	RetryCount    int32
	NextAttemptAt pgtype.Timestamptz
	CreatedAt     pgtype.Timestamptz
	ProcessedAt   pgtype.Timestamptz
}

// 複数ワーカーの二重取得を防ぐためSKIP LOCKEDを使う
func (q *Queries) FetchPendingOutbox(ctx context.Context, limit int32) ([]FetchPendingOutboxRow, error) {
	rows, err := q.db.Query(ctx, fetchPendingOutbox, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FetchPendingOutboxRow{}
	for rows.Next() {
		var i FetchPendingOutboxRow
		if err := rows.Scan(
			&i.ID,
			&i.EventType,
			&i.Payload,
			&i.Status,
			&i.RetryCount,
			&i.NextAttemptAt,
			&i.CreatedAt,
			&i.ProcessedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOutboxEvents = `-- name: ListOutboxEvents :many
SELECT id, event_type, payload, status, retry_count, next_attempt_at, last_error, created_at, processed_at
FROM outbox_events
ORDER BY created_at DESC
LIMIT $1
`

func (q *Queries) ListOutboxEvents(ctx context.Context, limit int32) ([]OutboxEvent, error) {
	rows, err := q.db.Query(ctx, listOutboxEvents, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OutboxEvent{}
	for rows.Next() {
		var i OutboxEvent
		if err := rows.Scan(
			&i.ID,
			&i.EventType,
			&i.Payload,
			&i.Status,
			&i.RetryCount,
			&i.NextAttemptAt,
			&i.LastError,
			&i.CreatedAt,
			&i.ProcessedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOutboxDone = `-- name: MarkOutboxDone :exec
UPDATE outbox_events SET status = 'done', processed_at = now(), last_error = NULL WHERE id = $1
`

func (q *Queries) MarkOutboxDone(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, markOutboxDone, id)
	return err
}

const markOutboxFailed = `-- name: MarkOutboxFailed :exec
UPDATE outbox_events SET status = 'failed', last_error = $2, retry_count = retry_count + 1 WHERE id = $1
`

type MarkOutboxFailedParams struct {
	ID        string
	LastError *string
}

func (q *Queries) MarkOutboxFailed(ctx context.Context, arg MarkOutboxFailedParams) error {
	_, err := q.db.Exec(ctx, markOutboxFailed, arg.ID, arg.LastError)
	return err
}

const markOutboxProcessing = `-- name: MarkOutboxProcessing :exec
UPDATE outbox_events SET status = 'processing' WHERE id = $1
`

func (q *Queries) MarkOutboxProcessing(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, markOutboxProcessing, id)
	return err
}

const rescheduleOutbox = `-- name: RescheduleOutbox :exec
UPDATE outbox_events
SET status = 'pending', retry_count = retry_count + 1, next_attempt_at = $2, last_error = $3
WHERE id = $1
`

type RescheduleOutboxParams struct {
	ID            string
	NextAttemptAt pgtype.Timestamptz
	LastError     *string
}

func (q *Queries) RescheduleOutbox(ctx context.Context, arg RescheduleOutboxParams) error {
	_, err := q.db.Exec(ctx, rescheduleOutbox, arg.ID, arg.NextAttemptAt, arg.LastError)
	return err
}
