// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payments.sql

package sqlc

import (
	"context"
)

const addRefundedAmount = `-- name: AddRefundedAmount :one
UPDATE payments
SET refunded_jpy = refunded_jpy + $2, updated_at = now()
WHERE id = $1
RETURNING id, amount_jpy, refunded_jpy, state
`

type AddRefundedAmountParams struct {
	ID          string
	RefundedJpy int64
}

type AddRefundedAmountRow struct {
	ID          string
	AmountJpy   int64
	RefundedJpy int64
	State       PaymentState
}

func (q *Queries) AddRefundedAmount(ctx context.Context, arg AddRefundedAmountParams) (AddRefundedAmountRow, error) {
	row := q.db.QueryRow(ctx, addRefundedAmount, arg.ID, arg.RefundedJpy)
	var i AddRefundedAmountRow
	err := row.Scan(
		&i.ID,
		&i.AmountJpy,
		&i.RefundedJpy,
		&i.State,
	)
	return i, err
}

const createPayment = `-- name: CreatePayment :one
INSERT INTO payments (id, product_id, amount_jpy, state)
VALUES ($1, $2, $3, 'created')
RETURNING id, product_id, amount_jpy, refunded_jpy, state, stripe_payment_intent_id, created_at, updated_at
`

type CreatePaymentParams struct {
	ID        string
	ProductID string
	AmountJpy int64
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error) {
	row := q.db.QueryRow(ctx, createPayment, arg.ID, arg.ProductID, arg.AmountJpy)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.AmountJpy,
		&i.RefundedJpy,
		&i.State,
		&i.StripePaymentIntentID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPayment = `-- name: GetPayment :one
SELECT id, product_id, amount_jpy, refunded_jpy, state, stripe_payment_intent_id, created_at, updated_at
FROM payments
WHERE id = $1
`

func (q *Queries) GetPayment(ctx context.Context, id string) (Payment, error) {
	row := q.db.QueryRow(ctx, getPayment, id)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.AmountJpy,
		&i.RefundedJpy,
		&i.State,
		&i.StripePaymentIntentID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPaymentForUpdate = `-- name: GetPaymentForUpdate :one
SELECT id, product_id, amount_jpy, refunded_jpy, state, stripe_payment_intent_id, created_at, updated_at
FROM payments
WHERE id = $1
FOR UPDATE
`

func (q *Queries) GetPaymentForUpdate(ctx context.Context, id string) (Payment, error) {
	row := q.db.QueryRow(ctx, getPaymentForUpdate, id)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.AmountJpy,
		&i.RefundedJpy,
		&i.State,
		&i.StripePaymentIntentID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertPaymentTransition = `-- name: InsertPaymentTransition :exec
INSERT INTO payment_transitions (id, payment_id, from_state, to_state, event, actor)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertPaymentTransitionParams struct {
	ID        string
	PaymentID string
	FromState PaymentState
	ToState   PaymentState
	Event     string
	Actor     string
}

func (q *Queries) InsertPaymentTransition(ctx context.Context, arg InsertPaymentTransitionParams) error {
	_, err := q.db.Exec(ctx, insertPaymentTransition,
		arg.ID,
		arg.PaymentID,
		arg.FromState,
		arg.ToState,
		arg.Event,
		arg.Actor,
	)
	return err
}

const listPaymentTransitions = `-- name: ListPaymentTransitions :many
SELECT id, payment_id, from_state, to_state, event, actor, created_at
FROM payment_transitions
WHERE payment_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListPaymentTransitions(ctx context.Context, paymentID string) ([]PaymentTransition, error) {
	rows, err := q.db.Query(ctx, listPaymentTransitions, paymentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PaymentTransition{}
	for rows.Next() {
		var i PaymentTransition
		if err := rows.Scan(
			&i.ID,
			&i.PaymentID,
			&i.FromState,
			&i.ToState,
			&i.Event,
			&i.Actor,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPayments = `-- name: ListPayments :many
SELECT id, product_id, amount_jpy, refunded_jpy, state, stripe_payment_intent_id, created_at, updated_at
FROM payments
WHERE ($3::payment_state IS NULL OR state = $3::payment_state)
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListPaymentsParams struct {
	Limit  int32
	Offset int32
	State  *PaymentState
}

func (q *Queries) ListPayments(ctx context.Context, arg ListPaymentsParams) ([]Payment, error) {
	rows, err := q.db.Query(ctx, listPayments, arg.Limit, arg.Offset, arg.State)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Payment{}
	for rows.Next() {
		var i Payment
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.AmountJpy,
			&i.RefundedJpy,
			&i.State,
			&i.StripePaymentIntentID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setStripePaymentIntent = `-- name: SetStripePaymentIntent :exec
UPDATE payments SET stripe_payment_intent_id = $2, updated_at = now() WHERE id = $1
`

type SetStripePaymentIntentParams struct {
	ID                    string
	StripePaymentIntentID *string
}

func (q *Queries) SetStripePaymentIntent(ctx context.Context, arg SetStripePaymentIntentParams) error {
	_, err := q.db.Exec(ctx, setStripePaymentIntent, arg.ID, arg.StripePaymentIntentID)
	return err
}

const updatePaymentState = `-- name: UpdatePaymentState :one
UPDATE payments
SET state = $2, updated_at = now()
WHERE id = $1 AND state = $3
RETURNING id, product_id, amount_jpy, refunded_jpy, state, stripe_payment_intent_id, created_at, updated_at
`

type UpdatePaymentStateParams struct {
	ID      string
	State   PaymentState
	State_2 PaymentState
}

func (q *Queries) UpdatePaymentState(ctx context.Context, arg UpdatePaymentStateParams) (Payment, error) {
	row := q.db.QueryRow(ctx, updatePaymentState, arg.ID, arg.State, arg.State_2)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.AmountJpy,
		&i.RefundedJpy,
		&i.State,
		&i.StripePaymentIntentID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
