// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: products.sql

package sqlc

import (
	"context"
)

const getProduct = `-- name: GetProduct :one
SELECT id, name, price_jpy, tokusho_snapshot, created_at
FROM products
WHERE id = $1
`

func (q *Queries) GetProduct(ctx context.Context, id string) (Product, error) {
	row := q.db.QueryRow(ctx, getProduct, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PriceJpy,
		&i.TokushoSnapshot,
		&i.CreatedAt,
	)
	return i, err
}

const listProducts = `-- name: ListProducts :many
SELECT id, name, price_jpy, tokusho_snapshot, created_at
FROM products
ORDER BY created_at DESC
LIMIT $1
`

func (q *Queries) ListProducts(ctx context.Context, limit int32) ([]Product, error) {
	rows, err := q.db.Query(ctx, listProducts, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Product{}
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.PriceJpy,
			&i.TokushoSnapshot,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertProduct = `-- name: UpsertProduct :exec
INSERT INTO products (id, name, price_jpy, tokusho_snapshot)
VALUES ($1, $2, $3, $4)
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, price_jpy = EXCLUDED.price_jpy, tokusho_snapshot = EXCLUDED.tokusho_snapshot
`

type UpsertProductParams struct {
	ID              string
	Name            string
	PriceJpy        int64
	TokushoSnapshot []byte
}

func (q *Queries) UpsertProduct(ctx context.Context, arg UpsertProductParams) error {
	_, err := q.db.Exec(ctx, upsertProduct,
		arg.ID,
		arg.Name,
		arg.PriceJpy,
		arg.TokushoSnapshot,
	)
	return err
}
