// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"
)

type Querier interface {
	AddRefundedAmount(ctx context.Context, arg AddRefundedAmountParams) (AddRefundedAmountRow, error)
	CreateAdminSession(ctx context.Context, arg CreateAdminSessionParams) error
	CreateAdminUser(ctx context.Context, arg CreateAdminUserParams) (AdminUser, error)
	CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error)
	DeleteAdminSession(ctx context.Context, id string) error
	DeleteExpiredIdempotency(ctx context.Context) (int64, error)
	EnqueueOutboxEvent(ctx context.Context, arg EnqueueOutboxEventParams) (EnqueueOutboxEventRow, error)
	// 複数ワーカーの二重取得を防ぐためSKIP LOCKEDを使う
	FetchPendingOutbox(ctx context.Context, limit int32) ([]FetchPendingOutboxRow, error)
	GetAdminSession(ctx context.Context, id string) (AdminSession, error)
	GetAdminUserByEmail(ctx context.Context, email string) (AdminUser, error)
	GetIdempotency(ctx context.Context, key string) (IdempotencyKey, error)
	GetIdempotencyByPaymentID(ctx context.Context, paymentID *string) (IdempotencyKey, error)
	GetPayment(ctx context.Context, id string) (Payment, error)
	GetPaymentForUpdate(ctx context.Context, id string) (Payment, error)
	GetProduct(ctx context.Context, id string) (Product, error)
	InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error
	// transfer_id + side の複合UNIQUE制約により、Outboxリトライ再実行では二重記帳を防ぐ
	InsertLedgerEntry(ctx context.Context, arg InsertLedgerEntryParams) error
	InsertPaymentTransition(ctx context.Context, arg InsertPaymentTransitionParams) error
	ListAuditLogs(ctx context.Context, limit int32) ([]AuditLog, error)
	ListLedgerByPayment(ctx context.Context, paymentID string) ([]LedgerEntry, error)
	ListOutboxEvents(ctx context.Context, limit int32) ([]OutboxEvent, error)
	ListPaymentTransitions(ctx context.Context, paymentID string) ([]PaymentTransition, error)
	ListPayments(ctx context.Context, arg ListPaymentsParams) ([]Payment, error)
	ListProducts(ctx context.Context, limit int32) ([]Product, error)
	ListWebhookEvents(ctx context.Context, limit int32) ([]WebhookEvent, error)
	MarkOutboxDone(ctx context.Context, id string) error
	MarkOutboxFailed(ctx context.Context, arg MarkOutboxFailedParams) error
	MarkOutboxProcessing(ctx context.Context, id string) error
	MarkWebhookProcessed(ctx context.Context, id string) error
	RescheduleOutbox(ctx context.Context, arg RescheduleOutboxParams) error
	SetIdempotencyResponse(ctx context.Context, arg SetIdempotencyResponseParams) error
	SetStripePaymentIntent(ctx context.Context, arg SetStripePaymentIntentParams) error
	SumLedgerBalance(ctx context.Context, account LedgerAccount) (SumLedgerBalanceRow, error)
	// 冪等性キー行を挿入する。既存キーとの競合時は0行を返す（呼び出し側でGetIdempotencyを実行して結果を返却する）
	TryInsertIdempotency(ctx context.Context, arg TryInsertIdempotencyParams) (IdempotencyKey, error)
	// stripe_event_idのUNIQUE制約で再配信を冪等化する。競合時は0行を返す
	TryInsertWebhookEvent(ctx context.Context, arg TryInsertWebhookEventParams) (WebhookEvent, error)
	UpdatePaymentState(ctx context.Context, arg UpdatePaymentStateParams) (Payment, error)
	UpsertProduct(ctx context.Context, arg UpsertProductParams) error
}

var _ Querier = (*Queries)(nil)
