// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: webhook.sql

package sqlc

import (
	"context"
)

const listWebhookEvents = `-- name: ListWebhookEvents :many
SELECT id, stripe_event_id, event_type, payload, status, received_at, processed_at
FROM webhook_events
ORDER BY received_at DESC
LIMIT $1
`

func (q *Queries) ListWebhookEvents(ctx context.Context, limit int32) ([]WebhookEvent, error) {
	rows, err := q.db.Query(ctx, listWebhookEvents, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WebhookEvent{}
	for rows.Next() {
		var i WebhookEvent
		if err := rows.Scan(
			&i.ID,
			&i.StripeEventID,
			&i.EventType,
			&i.Payload,
			&i.Status,
			&i.ReceivedAt,
			&i.ProcessedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markWebhookProcessed = `-- name: MarkWebhookProcessed :exec
UPDATE webhook_events SET status = 'processed', processed_at = now() WHERE id = $1
`

func (q *Queries) MarkWebhookProcessed(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, markWebhookProcessed, id)
	return err
}

const tryInsertWebhookEvent = `-- name: TryInsertWebhookEvent :one
INSERT INTO webhook_events (id, stripe_event_id, event_type, payload)
VALUES ($1, $2, $3, $4)
ON CONFLICT (stripe_event_id) DO NOTHING
RETURNING id, stripe_event_id, event_type, payload, status, received_at, processed_at
`

type TryInsertWebhookEventParams struct {
	ID            string
	StripeEventID string
	EventType     string
	Payload       []byte
}

// stripe_event_idのUNIQUE制約で再配信を冪等化する。競合時は0行を返す
func (q *Queries) TryInsertWebhookEvent(ctx context.Context, arg TryInsertWebhookEventParams) (WebhookEvent, error) {
	row := q.db.QueryRow(ctx, tryInsertWebhookEvent,
		arg.ID,
		arg.StripeEventID,
		arg.EventType,
		arg.Payload,
	)
	var i WebhookEvent
	err := row.Scan(
		&i.ID,
		&i.StripeEventID,
		&i.EventType,
		&i.Payload,
		&i.Status,
		&i.ReceivedAt,
		&i.ProcessedAt,
	)
	return i, err
}
